/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    public static void main(String[] args) {
//        System.out.println(new App().getGreeting());

	System.out.println("三項演算子のお試し");
        System.out.println("1-100までの数字を入れてください");
        System.out.println("1-79までは'不合格'、80-100までは'合格'と表示されます");

        Integer score = 100;
        Scanner scan = new Scanner(System.in);
	score = scan.nextInt();	

	String result = "";

// if文
        System.out.println("ifバージョン");

	if(score>=80){
		    result = "合格";
	}else{
		    result = "不合格";
	}
	System.out.println(result);

// 三項演算子 
        System.out.println("");
	System.out.println("三項演算子バージョン");

	result = (score >= 80)?"合格":"不合格";
	System.out.println(result);
    }
}
